In [10]:
import pandas as pd
import numpy as np

In [11]:
df_veneziane = pd.read_excel('data_raw/Aggiornamento_ART_COSTI_per_tipo_articoli_21-08_2023.xlsx', sheet_name='art_costi_veneziane')
df_veneziane['Codice_variante'] = df_veneziane['COD_ART_VAR_TIPO_COS_AZ_STDAG'].apply(lambda x: x.split('\\')[1]).astype(int)
df_veneziane.drop(columns=['COD_ART_VAR_TIPO_COS_AZ_STDAG','COD_ART_TIPO_COST'], inplace=True)
df_veneziane.rename(columns={'COD_ART':'Codice_articolo','COSTO_ART':'Costo','DATA_RIF':'Data_riferimento'}, inplace=True)
df_veneziane['Categoria'] = 'Veneziane'
df_veneziane['Descrizione'] = ''
df_veneziane = df_veneziane[['Codice_articolo','Codice_variante','Descrizione','Costo','Data_riferimento','Categoria']]
df_veneziane.head()

  Codice_articolo  Codice_variante  Costo Data_riferimento  Categoria
0       017.PM419                1  46.52       2023-01-12  Veneziane
1       017.PM420                1  46.52       2023-01-12  Veneziane
2       017.PM421                1  48.75       2023-01-12  Veneziane
3       017.PM422                3  46.52       2023-01-12  Veneziane
4       017.PM423                1  46.52       2023-01-12  Veneziane

In [24]:
#df_veneziane.info()

In [25]:
#df_veneziane.describe()

In [21]:
df_vetro = pd.read_excel('data_raw/Aggiornamento_ART_COSTI_per_tipo_articoli_21-08_2023.xlsx', sheet_name='Vetri')
df_vetro['Codice_variante'] = df_vetro['COD_ART_VAR_TIPO_COS_AZ_STDAG'].apply(lambda x: x.split('\\')[1])
df_vetro['Codice_variante'] = df_vetro['Codice_variante'].apply(lambda x: 0 if x == 'ATT' else x).astype(int)
df_vetro.drop(columns=['COD_ART_VAR_TIPO_COS_AZ_STDAG','COD_TIPO_COST','Codice Vetro', 'Costo Vetro', 'Unnamed: 8'], inplace=True)
df_vetro.rename(columns={'COD_ART':'Codice_articolo','COSTO_ART':'Costo','DATA_RIF':'Data_riferimento',"descrizione":"Descrizione"}, inplace=True)
df_vetro['Categoria'] = 'Vetri'
df_vetro = df_vetro[['Codice_articolo','Codice_variante','Descrizione','Costo','Data_riferimento','Categoria']]
df_vetro

,Codice_articolo,Codice_variante,Descrizione,Costo,Data_riferimento,Categoria
0,017.PM152,1,VETRO STRATIFICATO 33.1,30.5,2023-08-28,Vetri
1,017.PM152,2,VETRO STRATIFICATO 33.1,18.0,2023-08-28,Vetri
2,017.PM152,3,VETRO STRATIFICATO 33.1,30.5,2023-08-28,Vetri
3,017.PM152,4,VETRO STRATIFICATO 33.1,18.0,2023-08-28,Vetri
4,017.PM152,5,VETRO STRATIFICATO 33.1,18.0,2023-08-28,Vetri
...,...,...,...,...,...,...
587,090.VTT6,16,VETRO TRASPARENTE TEMPERATO 6 mm F.G. ANTA INT...,46.0,2023-08-28,Vetri
588,090.VTT6,17,VETRO TRASPARENTE TEMPERATO 6 mm F.G. ANTA INT...,46.0,2023-08-28,Vetri
589,090.VTT6,18,VETRO TRASPARENTE TEMPERATO 6 mm F.G. ANTA INT...,46.0,2023-08-28,Vetri
590,090.VTT6,19,VETRO TRASPARENTE TEMPERATO 6 mm F.G. ANTA INT...,46.0,2023-08-28,Vetri
591,090.VTT6,20,VETRO TRASPARENTE TEMPERATO 6 mm F.G. ANTA INT...,46.0,2023-08-28,Vetri

In [26]:
#df_vetro.info()

In [27]:
#df_vetro.describe()

In [32]:
df_ante_vetro = pd.read_excel('data_raw/Aggiornamento_ART_COSTI_per_tipo_articoli_21-08_2023.xlsx', sheet_name='Ante vetro')
df_ante_vetro['Codice_variante'] = df_ante_vetro['COD_ART_VAR_TIPO_COS_AZ_STDAG'].apply(lambda x: x.split('\\')[1])
df_ante_vetro['Codice_variante'] = df_ante_vetro['Codice_variante'].apply(lambda x: 0 if x == 'ATT' else x).astype(int)
df_ante_vetro.drop(columns=[
    'COD_ART_VAR_TIPO_COS_AZ_STDAG','COD_TIPO_COST',
    'LUNGH', 'LARGH', 'ALT', 'costo vetro', 'mq', 'LAV', 'N.fori', 'costo lav.'
    ], inplace=True)
df_ante_vetro.rename(columns={'COD_ART':'Codice_articolo','COSTO_ART':'Costo','DATA_RIF':'Data_riferimento',"DESCRIZIONE":"Descrizione"}, inplace=True)
df_ante_vetro['Categoria'] = 'Vetri'
df_ante_vetro = df_ante_vetro[['Codice_articolo','Codice_variante','Descrizione','Costo','Data_riferimento','Categoria']]
df_ante_vetro

,Codice_articolo,Codice_variante,Descrizione,Costo,Data_riferimento,Categoria
0,017.PM106.001,0,ANTA APR. SX o DX IN CRISTALLO TRASPARENTE 895...,128,2023-08-28,Vetri
1,017.PM106.002,0,ANTA APR. SX o DX IN CRISTALLO TRASPARENTE 895...,153,2023-08-28,Vetri
2,017.PM106.005,0,ANTA SEMIFISSA SX o DX IN CRISTALLO TRAS. 944x...,133,2023-08-28,Vetri
3,017.PM106.006,0,ANTA SEMIFISSA SX o DX IN CRISTALLO TRAS. 944 ...,159,2023-08-28,Vetri
4,017.PM106.007,0,ANTA SEMIFISSA SX o DX IN CRISTALLO TRAS. 193x...,43,2023-08-28,Vetri
...,...,...,...,...,...,...
67,092.ANTASCOP.04S,0,ANTA SCORREVOLE SX IN CRISTALLO OPACO. 1290 H=...,274,2023-08-28,Vetri
68,092.ANTASCOP.05D,0,ANTA SCORREVOLE DX IN CRISTALLO OPACO. 1290 H=...,306,2023-08-28,Vetri
69,092.ANTASCOP.05S,0,ANTA SCORREVOLE SX IN CRISTALLO OPACO. 1290 H=...,306,2023-08-28,Vetri
70,092.ANTASCOP.06D,0,ANTA SCORREVOLE DX IN CRISTALLO OPACO. 1290 H=...,331,2023-08-28,Vetri
71,092.ANTASCOP.06S,0,ANTA SCORREVOLE SX IN CRISTALLO OPACO. 1290 H=...,331,2023-08-28,Vetri

In [34]:
#df_ante_vetro.info()

In [36]:
#df_ante_vetro.describe()

In [41]:
df_visive = pd.read_excel('data_raw/Aggiornamento_ART_COSTI_per_tipo_articoli_21-08_2023.xlsx', sheet_name='Visive')
df_visive['Codice_variante'] = df_visive['COD_ART_VAR_TIPO_COS_AZ_STDAG'].apply(lambda x: x.split('\\')[1])
df_visive['Codice_variante'] = df_visive['Codice_variante'].apply(lambda x: 0 if x == 'ATT' else x).astype(int)
df_visive.drop(columns=[
    'COD_ART_VAR_TIPO_COS_AZ_STDAG','COD_TIPO_COST',
    'COSTO_ART_OLD', '%',
    ], inplace=True)
df_visive.rename(columns={'COD_ART':'Codice_articolo','COSTO_ART':'Costo','DATA_RIF':'Data_riferimento',"Descrizoine":"Descrizione"}, inplace=True)
df_visive['Categoria'] = 'Vetri'
df_visive = df_ante_vetro[['Codice_articolo','Codice_variante','Descrizione','Costo','Data_riferimento','Categoria']]
df_visive

,Codice_articolo,Codice_variante,Descrizione,Costo,Data_riferimento,Categoria
0,017.PM106.001,0,ANTA APR. SX o DX IN CRISTALLO TRASPARENTE 895...,128,2023-08-28,Vetri
1,017.PM106.002,0,ANTA APR. SX o DX IN CRISTALLO TRASPARENTE 895...,153,2023-08-28,Vetri
2,017.PM106.005,0,ANTA SEMIFISSA SX o DX IN CRISTALLO TRAS. 944x...,133,2023-08-28,Vetri
3,017.PM106.006,0,ANTA SEMIFISSA SX o DX IN CRISTALLO TRAS. 944 ...,159,2023-08-28,Vetri
4,017.PM106.007,0,ANTA SEMIFISSA SX o DX IN CRISTALLO TRAS. 193x...,43,2023-08-28,Vetri
...,...,...,...,...,...,...
67,092.ANTASCOP.04S,0,ANTA SCORREVOLE SX IN CRISTALLO OPACO. 1290 H=...,274,2023-08-28,Vetri
68,092.ANTASCOP.05D,0,ANTA SCORREVOLE DX IN CRISTALLO OPACO. 1290 H=...,306,2023-08-28,Vetri
69,092.ANTASCOP.05S,0,ANTA SCORREVOLE SX IN CRISTALLO OPACO. 1290 H=...,306,2023-08-28,Vetri
70,092.ANTASCOP.06D,0,ANTA SCORREVOLE DX IN CRISTALLO OPACO. 1290 H=...,331,2023-08-28,Vetri
71,092.ANTASCOP.06S,0,ANTA SCORREVOLE SX IN CRISTALLO OPACO. 1290 H=...,331,2023-08-28,Vetri

In [43]:
#df_visive.info()

In [45]:
#df_visive.describe()

In [49]:
df_ante_acciao = pd.read_excel('data_raw/Aggiornamento_ART_COSTI_per_tipo_articoli_21-08_2023.xlsx', sheet_name='Ante Acciaio')
df_ante_acciao['Codice_variante'] = df_ante_acciao['COD_ART_VAR_TIPO_COS_AZ_STDAG'].apply(lambda x: x.split('\\')[1])
df_ante_acciao['Codice_variante'] = df_ante_acciao['Codice_variante'].apply(lambda x: 0 if x == 'ATT' else x).astype(int)
df_ante_acciao.drop(columns=[
    'COD_ART_VAR_TIPO_COS_AZ_STDAG','COD_TIPO_COST',
    ], inplace=True)
df_ante_acciao.rename(columns={'COD_ART':'Codice_articolo','COSTO_ART':'Costo','DATA_RIF':'Data_riferimento',"Descrizione":"Descrizione"}, inplace=True)
df_ante_acciao['Categoria'] = 'Vetri'
df_ante_acciao = df_ante_acciao[['Codice_articolo','Codice_variante','Descrizione','Costo','Data_riferimento','Categoria']]
df_ante_acciao.head()

,Codice_articolo,Codice_variante,Descrizione,Costo,Data_riferimento,Categoria
0,017.PM105.01,7,ANTA IN ACCIAIO VERNICIATO DX 898 X 2043,300,2022-04-08,Vetri
1,017.PM105.03,4,ANTA IN ACCIAIO VERNICIATO SX 898 X 2043,300,2022-04-08,Vetri
2,017.PM105.05,2,ANTA APRIBILE IN ACCIAIO VERNICIATO DX 948 X 2043,300,2022-04-08,Vetri
3,017.PM105.07,1,ANTA APRIBILE IN ACCIAIO VERNICIATO SX 948 X 2043,300,2022-04-08,Vetri
4,017.PM105.09,1,ANTA SEMIFISSA IN ACCIAIO VERNICIATO SX 945 X ...,300,2022-04-08,Vetri

In [52]:
#df_ante_acciao.info()

In [53]:
#df_ante_acciao.describe()